
# Specify the Cubic server connection.  This is a subset of the available
# options the client can specify to the server.  See 
# https://cobaltspeech.github.io/sdk-cubic/protobuf/autogen-doc-cubic-proto/#message-recognitionconfig
# for more details.
[Server]
    # Specify the server address as "<url>:<port>"
    Address = "127.0.0.1:2733"

    # Set to true if the server is running without a
    # secure (TLS) connection (not recommended for
    # production environments).
    Insecure = false

    # Specify the cubic model to use for the transcriptions.
    # This string should match one of the models defined in cubicsvr.cfg.toml
    # on the server. A server may have multiple models available and the client
    # code may use other means to determine which one to call for a given file.  
    # For simplicity, this example just assumes configuring one model at a time.
    ModelID = "1"

    # Idle Timeout of the created Recognizer. If no audio data is received by 
    # the recognizer for this duration, ongoing rpc calls will result in an error,
    # the recognizer will be destroyed and thus more audio may not be sent to the
    # same recognizer. The server may impose a limit on the maximum idle timeout
    # that can be specified, and if the value in this setting exceeds that serverside
    # value, calling StreamingRecognize will fail with an error.
    # IdleTimeout = 30
